List<Map<String, dynamic>> products = [
  {
    'id': 1,
    'brand':'Nike',
    'name': 'Air Max 270',
    'description': 'The Nike Air Max 270 is inspired by two icons of big Air: the Air Max 180 and the Air Max 93.',
    'price': 150.0,
    'sizes': [7, 8, 9, 10, 11],
    'imageUrl': 'images/footwears/nike_airmax.png',
    'quantity': 1
  },
  {
    'id': 2,
    'brand': 'Nike',
    'name': 'Air Jordan 4',
    'description': 'The Ultraboost 21 shoes give you amazing energy return and a soft, supportive feel.',
    'price': 180.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/airjordan4.png',
    'quantity': 1
  },
  {
    'id': 3,
    'brand': 'Nike',
    'name': 'Dunk Low',
    'description': 'The Ultraboost 21 shoes give you amazing energy return and a soft, supportive feel.',
    'price': 100.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/dunk_low.png',
    'quantity': 1,
  },
  {
    'id': 4,
    'brand': 'Nike',
    'name': 'Zoom Spiridon',
    'description': 'The Ultraboost 21 shoes give you amazing energy return and a soft, supportive feel.',
    'price': 120.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/zoom.png',
    'quantity': 1,
  },
  {
    'id': 5,
    'brand': 'Nike',
    'name': 'Airforce 1',
    'description': 'The Ultraboost 21 shoes give you amazing energy return and a soft, supportive feel.',
    'price': 180.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/airforce1.png',
    'quantity': 1,
  },
  {
    'id': 6,
    'brand': 'Adidas',
    'name': 'Yeezy Boost 350 V2', 
    'description': 'A part of Kanye West\'s iconic Yeezy collection, the Boost 350 V2 is known for its comfort, flexibility, and distinct design. It features a primeknit upper, Boost cushioning, and a sock-like fit, making it a favorite among sneakerheads',
    'price': 200.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/350V2.png',
    'quantity': 1,
  },
  {
    'id': 7,
    'brand': 'Adidas',
    'name': 'NMD_R1',
    'description': 'A blend of street style and running technology, the NMD_R1 features responsive Boost cushioning and a knit upper for a sleek, modern look. The shoe is lightweight and ideal for urban exploration.',
    'price': 150.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/nmd_R1.png',
    'quantity': 1,
  },
  {
    'id': 8,
    'brand': 'Adidas',
    'name': 'Forum Low',
    'description': 'A retro basketball-inspired sneaker that combines heritage with modern updates. The Forum Low boasts a mix of leather and synthetic upper, padded collar, and a durable outsole for all-day comfort..',
    'price': 150.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/forum_low.png',
    'quantity': 1,
  },
  {
    'id': 9,
    'brand': 'Adidas',
    'name': 'Ultraboost 22',
    'description': 'Built for comfort and performance, the Ultraboost 22 offers incredible energy return through its Boost midsole. The breathable Primeknit upper and Continental rubber outsole provide the perfect balance of flexibility and grip.',
    'price': 150.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/ultraboost21.png',
    'quantity': 1,
  },
  {
    'id': 10,
    'brand': 'Adidas',
    'name': 'SuperStar',
    'description': 'An iconic sneaker since the 70s, the Superstar is known for its clean lines, shell toe design, and durable leather upper. It remains a timeless choice for both casual wear and sports.',
    'price': 120.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl': 'images/footwears/superstar.png',
    'quantity': 1,
  },
  {
    'id': 11,
    'brand': 'New Balance',
    'name': 'NB 550',
    'description': 'The retro-styled 550 reintroduces a classic basketball design from the 80s. Featuring a leather upper, perforated overlays, and a cushioned midsole, it\'s perfect for vintage-inspired streetwear.',
    'price': 160.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/nbbanner.png',
    'quantity': 1,
  },
  {
    'id': 12,
    'brand': 'New Balance',
    'name': 'NB 2002R',
    'description': ' Combining early 2000s running shoe design with modern-day comfort, the 2002R features ABZORB cushioning, N-ergy shock absorption, and a sleek, minimalist design.',
    'price': 170.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/2002r.png',
    'quantity': 1,
  },
  {
    'id': 13,
    'brand': 'New Balance',
    'name': 'NB 90v5',
    'description': 'The 990v5 offers superior comfort, support, and style. This American-made classic features premium materials, ENCAP midsole technology, and a mesh upper for enhanced breathability.',
    'price': 150.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/990v5.png',
    'quantity': 1,
  },
  {
    'id': 14,
    'brand': 'New Balance',
    'name': 'NB 327',
    'description': ' Inspired by 1970s running shoes, the 327 is a modern twist on retro design. It features a lightweight construction, suede and nylon upper, and a unique oversized "N" logo.',
    'price': 280.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/327.png',
    'quantity': 1,
  },
  {
    'id': 15,
    'brand': 'New Balance',
    'name': 'NB XC-72',
    'description': 'With a futuristic silhouette and bold design elements, the XC-72 takes inspiration from retro athletics but with a modern, fashion-forward twist. It includes an angular sole and premium suede and leather materials.',
    'price': 300.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/xc-72.png',
    'quantity': 1,
  },
  {
    'id': 16,
    'brand': 'Vans',
    'name': 'Old Skool',
    'description': 'A timeless classic, the Old Skool is known for its durable canvas and suede construction, padded collar, and signature side stripe. It remains a staple in skateboarding culture and casual fashion.',
    'price': 90.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/old_skool.png',
    'quantity': 1,
  },
  {
    'id': 17,
    'brand': 'Vans',
    'name': 'Ultrarange vr3',
    'description': 'The Ultraboost 21 shoes give you amazing energy return and a soft, supportive feel.',
    'price': 280.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/ultrarange.png',
    'quantity': 1,
  },
  {
    'id': 18,
    'brand': 'Vans',
    'name': 'Vans Upland',
    'description': ' A high-top version of the Old Skool, the Sk8-Hi provides additional ankle support while maintaining a sleek silhouette. Its vulcanized rubber outsole ensures durability for both skating and street style.',
    'price': 65.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/upland.png',
    'quantity': 1,
  },
  {
    'id': 19,
    'brand': 'Vans',
    'name': 'Old Skool Overt',
    'description': 'The first Vans silhouette ever created, the Authentic has a low-top, lightweight design with a simple canvas upper and a rubber waffle outsole, making it a versatile everyday sneaker',

    'price': 70.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/overt.png',
    'quantity': 1,
  },
  {
    'id': 20,
    'brand': 'Vans',
    'name': 'Vans Era',
    'description': 'Known for its comfort and simplicity, the Era features padded collars and double-stitched canvas for extra durability. This iconic low-top sneaker is popular among skaters and casual wearers alike.',
    'price': 220.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/era.png',
    'quantity': 1,
  }
  
];
List<Map<String, dynamic>> discountedProducts = [
 {
    'id': 1,
    'brand':'Nike',
    'name': 'Air Max 270',
    'description': 'The Nike Air Max 270 is inspired by two icons of big Air: the Air Max 180 and the Air Max 93.',
    'price': 150.0,
    'sizes': [7, 8, 9, 10, 11],
    'imageUrl': 'images/footwears/nike_airmax.png',
    'quantity': 1
  },
  {
    'id': 2,
    'brand': 'Nike',
    'name': 'Air Jordan 4',
    'description': 'The Ultraboost 21 shoes give you amazing energy return and a soft, supportive feel.',
    'price': 180.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/airjordan4.png',
    'quantity': 1
  },
  {
    'id': 3,
    'brand': 'Nike',
    'name': 'Dunk Low',
    'description': 'The Ultraboost 21 shoes give you amazing energy return and a soft, supportive feel.',
    'price': 100.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/dunk_low.png',
    'quantity': 1,
  },
  {
    'id': 4,
    'brand': 'Nike',
    'name': 'Ultraboost 21',
    'description': 'The Ultraboost 21 shoes give you amazing energy return and a soft, supportive feel.',
    'price': 120.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/nike_airmax.png',
    'quantity': 1,
  },
  {
    'id': 5,
    'brand': 'Nike',
    'name': 'Airforce 1',
    'description': 'The Ultraboost 21 shoes give you amazing energy return and a soft, supportive feel.',
    'price': 180.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/airforce1.png',
    'quantity': 1,
  },
  {
    'id': 6,
    'brand': 'Adidas',
    'name': 'Yeezy Boost 350 V2', 
    'description': 'A part of Kanye West\'s iconic Yeezy collection, the Boost 350 V2 is known for its comfort, flexibility, and distinct design. It features a primeknit upper, Boost cushioning, and a sock-like fit, making it a favorite among sneakerheads',
    'price': 200.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/350V2.png',
    'quantity': 1,
  },
  {
    'id': 7,
    'brand': 'Adidas',
    'name': 'NMD_R1',
    'description': 'A blend of street style and running technology, the NMD_R1 features responsive Boost cushioning and a knit upper for a sleek, modern look. The shoe is lightweight and ideal for urban exploration.',
    'price': 150.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/nmd_R1.png',
    'quantity': 1,
  },
  {
    'id': 8,
    'brand': 'Adidas',
    'name': 'Forum Low',
    'description': 'A retro basketball-inspired sneaker that combines heritage with modern updates. The Forum Low boasts a mix of leather and synthetic upper, padded collar, and a durable outsole for all-day comfort..',
    'price': 150.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/forum_low.png',
    'quantity': 1,
  },
  {
    'id': 9,
    'brand': 'Adidas',
    'name': 'Ultraboost 22',
    'description': 'Built for comfort and performance, the Ultraboost 22 offers incredible energy return through its Boost midsole. The breathable Primeknit upper and Continental rubber outsole provide the perfect balance of flexibility and grip.',
    'price': 150.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/nike_airmax.png',
    'quantity': 1,
  },
  {
    'id': 10,
    'brand': 'Adidas',
    'name': 'SuperStar',
    'description': 'An iconic sneaker since the 70s, the Superstar is known for its clean lines, shell toe design, and durable leather upper. It remains a timeless choice for both casual wear and sports.',
    'price': 120.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl': 'images/footwears/nike_airmax.png',
    'quantity': 1,
  },
  {
    'id': 11,
    'brand': 'New Balance',
    'name': 'New Balance 550',
    'description': 'The retro-styled 550 reintroduces a classic basketball design from the 80s. Featuring a leather upper, perforated overlays, and a cushioned midsole, it\'s perfect for vintage-inspired streetwear.',
    'price': 160.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/nbbanner.png',
    'quantity': 1,
  },
  {
    'id': 12,
    'brand': 'New Balance',
    'name': 'New Balance 2002R',
    'description': ' Combining early 2000s running shoe design with modern-day comfort, the 2002R features ABZORB cushioning, N-ergy shock absorption, and a sleek, minimalist design.',
    'price': 170.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/nike_airmax.png',
    'quantity': 1,
  },
  {
    'id': 13,
    'brand': 'New Balance',
    'name': 'New Balance 90v5',
    'description': 'The 990v5 offers superior comfort, support, and style. This American-made classic features premium materials, ENCAP midsole technology, and a mesh upper for enhanced breathability.',
    'price': 150.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/nike_airmax.png',
    'quantity': 1,
  },
  {
    'id': 14,
    'brand': 'New Balance',
    'name': 'New Balance 327',
    'description': ' Inspired by 1970s running shoes, the 327 is a modern twist on retro design. It features a lightweight construction, suede and nylon upper, and a unique oversized "N" logo.',
    'price': 280.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/nike_airmax.png',
    'quantity': 1,
  },
  {
    'id': 15,
    'brand': 'New Balance',
    'name': 'New Balance XC-72',
    'description': 'With a futuristic silhouette and bold design elements, the XC-72 takes inspiration from retro athletics but with a modern, fashion-forward twist. It includes an angular sole and premium suede and leather materials.',
    'price': 300.0,
    'sizes': [6, 7, 8, 9, 10, 11, 12],
    'imageUrl':  'images/footwears/nike_airmax.png',
    'quantity': 1,
  },
];