// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLfY8UpbZjDg08q6CiqmT5-JLBMCZrYFY',
    appId: '1:884107786471:web:1210dc9f3fb98be2660a42',
    messagingSenderId: '884107786471',
    projectId: 'buggies-shoe-store-app',
    authDomain: 'buggies-shoe-store-app.firebaseapp.com',
    storageBucket: 'buggies-shoe-store-app.appspot.com',
    measurementId: 'G-R2KKL49LPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChlXZhS6EMOHOenSlxkGw3kLMGHP3Zmp0',
    appId: '1:884107786471:android:26f0c9ec662bc2a2660a42',
    messagingSenderId: '884107786471',
    projectId: 'buggies-shoe-store-app',
    storageBucket: 'buggies-shoe-store-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfr5iQHevBsktXz8wzgfOJnjG3SkCSjfY',
    appId: '1:884107786471:ios:148eac5fe7fc57f1660a42',
    messagingSenderId: '884107786471',
    projectId: 'buggies-shoe-store-app',
    storageBucket: 'buggies-shoe-store-app.appspot.com',
    iosBundleId: 'com.example.sneakerStoreApp',
  );
}
